image: mcr.microsoft.com/dotnet/framework/sdk:4.8

stages:
  - build
  - publish

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - publish/
    - .nuget/

build:
  stage: build
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - .nuget/
  before_script:
    - dotnet restore -s "https://api.nuget.org/v3/index.json" --verbosity detailed --packages ./.nuget/
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
  variables:
    DOTNET_CONFIGURATION: "Release"
    RELEASE_VERSION: ""
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        DOTNET_CONFIGURATION: "Release-beta"
        RELEASE_VERSION: "-p:Version=1.0.0-beta"
    - if: ($CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/ || $CI_COMMIT_BRANCH == "z_main" || $CI_COMMIT_BRANCH == "staging" || $CI_PIPELINE_SOURCE == 'merge_request_event')
  script:
    - echo Publishing in $DOTNET_CONFIGURATION
    - "dotnet publish -c $DOTNET_CONFIGURATION $RELEASE_VERSION -o ./publish ./src/OpenAC.Net.Core.csproj "


publish:
  stage: publish
  before_script:
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
  script:
    - dotnet nuget push "bin/Release*/*.nupkg" --timeout 600 --source gitlab
  only:
    - z_main
    - staging



